### ISSUE TITLE
name repos properly

### ISSUE THREAD

**Issue by OlivierJM** [Deewiliams/javascript-questions-answers#2]
it is good to be consistent with naming repos, the best examples is to keep all letters in lower camps and avoid unnecessary characters like this one I would suggest this "javascript-questions-answer" this is good because it is also consistent with the url of the repo as well.

**Comment by Deewiliams** [comment]
alright thanks, i appreciate i will change the repo name.

**Comment by OlivierJM** [comment]
awesome

**Comment by OlivierJM** [comment]
closing this since the repo is renamed
