### ISSUE TITLE
bigger number question

### ISSUE THREAD

**Issue by Deewiliams** [Deewiliams/javascript-questions-answers#4]
am kind of trying to understand if i console.log  the two argument (2,3), the output should be  3 right.?
and should i use a loop to solve this question?

**Comment by OlivierJM** [comment]
Hi @Deewiliams rename the title of the issue to match the question like "bigger number question"

Then regarding your clarification, it should be like this if your function is called biggerNumber(2, 3) then it should log 3 because is bigger.
To verify if your function works, give it different values like below and see if it still gives you a bigger number

```javascript
biggerNumber(2, 3)  // 3
biggerNumber(12, 3) // 12
biggerNumber(0, -3)  // 0
```

**Comment by OlivierJM** [comment]
A hint for this https://github.com/Deewiliams/javascript-questions-answers/blob/4c85ebd88df4c2e63c75f4fdbf24d3a9d3f18dd5/index.js#L85
You need to pass 2 parameters that represent the 2 numbers you are comparing, remember 2 and 3 are just examples, the function should do its job despite the given numbers.

**Comment by OlivierJM** [comment]
You can consider functions like the same functions in math, where you can have something like `f(x) = x + 2` or `f(x, y) = x + y ` then if `f(2) = 2 + 2` or `f(2, 1) = 2 + 1` they are pretty much the same.

**Comment by OlivierJM** [comment]
@Deewiliams let me know if the explanation above made sense.

**Comment by Deewiliams** [comment]
The explanation is okay and I understood it,am trying to implement it and I
think I have managed now

**Comment by Deewiliams** [comment]
Try and review my other solution

**Comment by OlivierJM** [comment]
Awesome the solution is okay, so you don't need to use the `parseInt` only use it when the values are not integers, like "1" and this way make sure you use parseInt before any operations like comparison or others. 
Then following what the questions was saying you can simplify your solution to this

```javascript

//Write a function named biggerNumber that takes 2 arguments, both numbers returns whichever number is the greater (higher) number, so if you give 2, 3 then it should 3.

// You need the = only use that when you want to include the number itself
function biggerNumber(num, num1) {
  if (num > num1) {
    return num;
  } else if (num < num1) {
    return num1;
  }
}

// Here you only check if the num is bigger than num1 and since one can only bigger, if it is not then you return the other one 
function biggerNumber(num, num1) {
  if (num > num1) {
    return num;
  } 
  return num1;
}
```

Both solutions above and yours should all work the same

**Comment by Deewiliams** [comment]
Alright thanks for the clarification....have taken note of it.

**Comment by OlivierJM** [comment]
Yeahh otherwise this is good Dee. for other exercises, create individual files inside this repo instead of using just the index.js

so in this case you can have bigger_number.js as a file and you put the solution in there, this way it is easier to find things

**Comment by OlivierJM** [comment]
Let me know if you have questions regarding the second question, it might be trickier.

**Comment by Deewiliams** [comment]
okay i will be creating  the files in that way and i will create an issue on the second question as well.

**Comment by OlivierJM** [comment]
Awesome, I am closing this since we are done with it. Thanks a lot and keep it up

**Comment by OlivierJM** [comment]
Closed issues are still available in case you need to refer to them at any point.  actually I don't have access to close it, you can go ahead and close it.

**Comment by Deewiliams** [comment]
Alright, actually thanks to you,looking forward for more questions when am done with the second one. and am closing the issue now.
