### ISSUE TITLE
fizzbuzz-question

### ISSUE THREAD

**Issue by Deewiliams** [Deewiliams/javascript-questions-answers#5]

**Comment by OlivierJM** [comment]
@Deewiliams let's try it without a loop   

https://github.com/Deewiliams/javascript-questions-answers/blob/main/FizzBuzz.js#L3

**Comment by OlivierJM** [comment]
remember it is just one number we are giving the function so we shouldn't need to loop anything

**Comment by Deewiliams** [comment]
alright and check what i have done on the second one.

**Comment by Deewiliams** [comment]
Hey Ollie i believe this one is working just modified it.

**Comment by OlivierJM** [comment]
let me check

**Comment by OlivierJM** [comment]
This looks good Dee, will give you other assignements

**Comment by OlivierJM** [comment]
You can close the issue.

**Comment by Deewiliams** [comment]
alright cool, i'll be waiting for more.
